### ISSUE TITLE
r-01-introduction - missing welcome script

### ISSUE THREAD

**Issue by dkcoxie** [umich-brcf-bioinf/2023-07-31-umich-computational-foundations#11]
For "Orienting on RStudio" section, the `welcome.R` script is missing - it's neither in the home directory or in the `CF_R` folder. 

When it's added to learner's directories, some edits to the directions in the instructor notes might be needed as some navigation is needed to get to the R materials from the home directory (home/CF_R/<data/ + instructor_notes.txt>)

**Comment by rcavalcante** [comment]
Fixed by @cgates
