### ISSUE TITLE
r-01 and r-02: Consider only loading gapminder_1997 in module 2

### ISSUE THREAD

**Issue by dkcoxie** [umich-brcf-bioinf/2023-07-31-umich-computational-foundations#12]
`gapminder_1997` data is loaded early in intro module (before explaining functions) but not looked at/used in that; consider editing both to remove code from first section and then editing text / description in module 2.

**Comment by rcavalcante** [comment]
I could see how this would work without loading the data, but, for now, I think I'll leave this in to see how it goes. There might be utility in showing up front how easy it is to load data, and it begs some questions about data types that are good to get into.
