### ISSUE TITLE
03 Data visualization - gapminder_1997_labels last column might not be visible for learners

### ISSUE THREAD

**Issue by dkcoxie** [umich-brcf-bioinf/2023-07-31-umich-computational-foundations#13]
Output of provided code block: 
```
gapminder_1997_labels = gapminder_1997 %>% 
+   mutate(label = ifelse(country %in% c('Brazil', 'China', 'India', 'United States'), country, ''))
```
Generated expected output but the new column (`label`) wasn't displayed with the rstudio server window limited to have my laptop screen. Might be worth moving that column earlier in the output table (e.g. with `.before = year` option in mutate function)

**Comment by dkcoxie** [comment]
Basically, a downside of tibbles making data in nicer formats is that it can obscure some of the columns, depending on window size.

**Comment by dkcoxie** [comment]
Note tested my suggestion and this code block works & makes the `label` column visible on my screen:
```
gapminder_1997_labels = gapminder_1997 %>% 
  mutate(label = ifelse(country %in% c('Brazil', 'China', 'India', 'United States'), country, ''), .before = year)
```

**Comment by rcavalcante** [comment]
Ah, yes, this often annoys me too, and I end up doing `tbl %>% head %>% data.frame` to have a look. While `.before` definitely fixes the problem, perhaps we'll leave it and if it does get chopped off, it's a good opportunity to point out this behavior (which they will inevitably see again) and how to fix it with `.before` or by coercing it to a data frame and looking at the head.
