### ISSUE TITLE
3 Data Visualization - surprising error for plot proceeding final exercise

### ISSUE THREAD

**Issue by dkcoxie** [umich-brcf-bioinf/2023-07-31-umich-computational-foundations#14]
Plot before final exercise in module triggered error:
```
ggplot(data = gapminder_data, aes(x = year, y = gdpPercap, color = continent, group = country)) +
    geom_line() + theme_bw() +
    labs(
        title = 'GDP per Capita 1952 - 2007',
        x = 'Year', y = 'GDP per Capita')
```

Error:
```
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)
```

Might be due to the size of my window (half screen), but did resolve after widening my plot panel and I was able to generate other plots without running into this error.

**Comment by rcavalcante** [comment]
Glad to know that making the window bigger fixed the problem. If this comes up, I think that'll be the suggestion we make. Thanks for discovering this!
